### ISSUE TITLE
Why does the NsOptions::Option::Boolean handler class exist?

### ISSUE THREAD

**Issue by kellyredding** [redding/ns-options#24]
I ask b/c it looks like the only way that class is used is one of the following ways:

```
MyTest
  include NsOptions

  options(:test) do
    option :foo, TrueClass
    option :bar, FalseClass
    option :baz, NsOptions::Option::Boolean
  end
```

Otherwise, type_class is Object and its not used (true/false values pass thru b/c they are kind_of? Object).  I submit to you that no user will ever (or want to) specify an option this way and it should just be removed and let the true/false pass thru behavior take care of this case.  You could put in a usable_type_class rule to make the type_class Object if, for some reason, someone does specify TrueClass or FalseClass as a type_class.

Can we just remove the Boolean class then?  @jcredding - thoughts?

**Comment by jcredding** [comment]
Handled with #25. The boolean class still exists, but it gets no special handling.
