### ISSUE TITLE
cleanups pre 1.0

### ISSUE THREAD

**Issue by kellyredding** [redding/ns-options#66]
- add me to authors
- add homepage
- assert 1.0

**Comment by jcredding** [comment]
@kellyredding - You should be an owner already: https://rubygems.org/gems/ns-options

**Comment by kellyredding** [comment]
@jcredding oops - meant authors.

**Comment by jcredding** [comment]
@kellyredding - The 3 mentioned so far are in: https://github.com/redding/ns-options/commit/3fdd54fd9bf7757a2196c4e77d0e59e16855bd2a.

Not sure if you are keeping this as a running list for now, so I'll leave it open.

**Comment by kellyredding** [comment]
No, this was just a reminder.  I can close this now.
