### ISSUE TITLE
Fix `CoerceError` handling bug

### ISSUE THREAD

**Issue by jcredding** [redding/ns-options#68]
On this line:

https://github.com/redding/ns-options/blob/master/lib/ns-options/namespace_data.rb#L139

the `err` that is trying to be passed is not defined. I believe we need to add it to the rescue line:

``` ruby
...
rescue NsOptions::Option::CoerceError => err
  error! bt, err # reraise this exception with a sane backtrace
...
```

**Comment by kellyredding** [comment]
@jcredding this means the test suite is lacking... yikes
