### ISSUE TITLE
NsOptions Struct

### ISSUE THREAD

**Issue by kellyredding** [redding/ns-options#75]
Just a thought:

``` ruby
require 'ns-options'

thing = NsOptions::Struct.new

class Thing < NsOptions::Struct.new
end
# or 
Thing = Class.new(NsOptions::Struct.new)
```

Not too much value over Struct/OpenStruct I know,  but...

``` ruby
Thing = Class.new(NsOptions::Struct.new do
  option :opt1, String, :default => 'something'
  option :opt2
end)

thing = Thing.new(:other => 123)
thing.other  #=> 123
thing.opt1   #=> 'something'
thing.opt2   #=> nil
thing.opt2 = 2
thing.yet_another = 'yay' 
```

An ns-options struct instance is a standalone proxy class you don't have to define ahead of time.  It has dynamic readers/writers like `OpenStruct` but the `new` method creates a class you can inherit from like `Struct`.

Practical application: handling hash arguments in methods

``` ruby
# indifferent access

def some_method(args={})
  the_args = NsOptions::Struct.new(args)
  # ... use the_args
end

# default arg values, type-casting...

MethodArgs = NsOptions::Struct.new do
  option :arg1, String, :default => 'something'
  option :arg2, Integer, :default => 2
end

def some_method(args={})
  the_args = MethodArgs.new(args)
  # ... use the_args
end

# alternative form....

def some_method(args={})
  the_args = NsOptions::Struct.new(args) do
    option :arg1, String, :default => 'something'
    option :arg2, Integer, :default => 2
  end
  # ... use the_args
end
```

@jcredding thoughts?

**Comment by jcredding** [comment]
@kellyredding - My first thought is how is the end result different from the `Proxy` mixin:

``` ruby
class MethodArgs
  include NsOptions::Proxy
  option :arg1, String, :default => 'something'
  option :arg2, Integer, :default => 2
end
```

I do like the struct pattern though, definitely reads better. Also, I'm not sure what kind of thing is actually being returned by `NsOptions::Struct.new`. By kind of thing, I mean is it a class (like `Struct`) or an instance (like `OpenStruct`). For example, based on your last example, can I call `the_args.new({ :something => true })`. I would expect this based on the `MethodArgs` usage above it.

**Comment by kellyredding** [comment]
@jcredding First off, it's different from a proxy in that it is _a creator_ of proxy classes.  I'd see the implementation going something like this:

``` ruby
module Struct
  def self.new(opts=nil, &block)
    Class.new.tap do |klass|
      klass.class_eval { include NsOptions::Proxy }
      klass.define(&block)
      klass.apply(opts)
    end
  end
end
```

Its really just a helper to create proxy classes for me so I don't have to manually create a class and manually mixin NsOptions::Proxy just to robustly handle some hash args.

These generated Classes would have a kinda hybrid behavior compared to `Struct` or `OpenStruct`.  It would be like a traditional `Struct` in that its new method creates a Class.  It would be like an `OpenStruct` in that those Classes would have dynamic readers and writers.  It would be unique (and kinda Struct-ish) in that I can predefine some options and default/type-cast them.

For the last example you would be able to call `the_args.new(:something => true)` because `the_args` would be a Class.  But, b/c NsOptions is what it is, you could just use `the_args` directly as well.

Does that clear up the intent?

**Comment by kellyredding** [comment]
@jcredding this is me playing with Github's new image attachment stuff

Dragged in:
![sweet jesus](http://alltheragefaces.com/img/faces/png/sweet-jesus.png)

Drag Uploaded:
![img-thing.jpeg](https://f.cloud.github.com/assets/82110/1502/3a39dd9a-40ef-11e2-996e-1b2dabc189c5.jpeg)

Chosen Uploaded:
![rage_face.jpg](https://f.cloud.github.com/assets/82110/1503/573f23d2-40ef-11e2-8006-249e28c288d6.jpg)

(ahh Markdown)
