### ISSUE TITLE
Equality issue

### ISSUE THREAD

**Issue by jcredding** [redding/ns-options#84]
There's a goofy equality issue that can happen when comparing namespaces. If you have the following:

``` ruby
class MyClass; end
class MyOptions
  include NsOptions::Proxy
  option :klass, Class, :default => MyClass
end

options = MyOptions.new
options == options # false
options.eql? options # true, are they the same object
```

The `==` operator for a namespace builds a hash version of itself options and uses that to compare them (https://github.com/redding/ns-options/blob/master/lib/ns-options/namespace.rb#L57). The `to_hash` method builds distinct values to avoid pass-by-ref via its `to_hash` method (https://github.com/redding/ns-options/blob/master/lib/ns-options/namespace_data.rb#L53). `NsOptions.distinct_value` clones objects (https://github.com/redding/ns-options/blob/master/lib/ns-options.rb#L12) to avoid the pass-by-ref biz.

So the issue is that if a `Class` gets cloned its clone is not equal to the original, thus the 2 hashes don't equal and the same object is not equal to itself even though they are the same object.

I think we should either add a special case if the left and right object are the same object return true or we might think about not cloning classes. Cloning classes works but it can be confusing:

``` ruby
# with the above definition
options = MyOptions.new
options.klass # => #<Class:0x10db2df50>
```

Whenever you use the option you don't get the named class that you set (in this case `MyClass`) instead you get an anonymous class.

**Comment by kellyredding** [comment]
@jcredding I'm going to close this as we aren't really using or working on ns-options anymore.
